name: build-llama-so
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nttld/setup-ndk@v1
        with: { ndk-version: r26d }
      - name: Build llama.cpp for ANDROID arm64 (no curl)
        run: |
          set -e
          git clone --depth=1 https://github.com/ggerganov/llama.cpp.git
          cmake -S llama.cpp -B build-llama-android \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-24 \
            -DBUILD_SHARED_LIBS=ON -DLLAMA_CURL=OFF \
            -DGGML_CUDA=OFF -DGGML_OPENCL=OFF -DGGML_METAL=OFF -DGGML_BLAS=OFF
          cmake --build build-llama-android -j
          mkdir -p out/arm64-v8a
          find build-llama-android -name libllama.so -print -exec cp {} out/arm64-v8a/ \;
      - uses: actions/upload-artifact@v4
        with:
          name: libllama-android-arm64
          path: out/arm64-v8a/libllama.so